version: '3.8'

networks:
  bs-network:
    driver: bridge

volumes:
  bs-data:
    driver: local

services:
  bs-nginx:
    image: nginx:1.25.3
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - bs-php
    networks:
      - bs-network

  bs-mysql:
    image: mysql:${MYSQL_VERSION}
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - bs-data:/var/lib/mysql
    command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    networks:
      - bs-network

  bs-php:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        UID: ${UID}
        GID: ${GID}
        XDEBUG_ENABLED: true
    container_name: bs-php
    volumes:
      - ./:/var/www/html
    ports:
      - "9001:9000"
    networks:
      - bs-network